image: isprasmvg/utopia-eda:clear

variables:
  UTOPIA_HOME: "/builds/${CI_PROJECT_PATH}"
  BUILD: "build"
  BUILD_PATH: "${UTOPIA_HOME}/${BUILD}"

stages:
  - build
  - test

build_project:
  stage: build
  tags:
    - docker

  script:
    - rm -rf ${BUILD_PATH}
    - cd ${UTOPIA_HOME}
    - git submodule init
    - git submodule update
    - cmake -S . -B ${BUILD} -G Ninja
    - cmake --build ${BUILD}

  artifacts:
    expire_in: 1 day
    paths:
      - ${BUILD_PATH}

test_project:
  stage: test
  tags:
    - docker

  script:
    - cd ${UTOPIA_HOME}
    - rm -rf ${UTOPIA_HOME}/output
    - ${BUILD_PATH}/test/utest

  dependencies:
    - build_project
