image: isprasmvg/utopia-eda:clear

variables:
  UTOPIA_HOME: "/builds/mvg/utopia-eda"

stages:
  - build
  - test

build_project:
  stage: build
  tags:
    - docker

  script:
    - rm -rf ${UTOPIA_HOME}/build
    - cd ${UTOPIA_HOME}
    - git submodule init
    - git submodule update
    - cmake -S . -B build -G Ninja
    - cmake --build build

  artifacts:
    paths:
      - ${UTOPIA_HOME}/build/

test_project:
  stage: test
  tags:
    - docker

  script:
    - cd ${UTOPIA_HOME}
    - rm -rf ${UTOPIA_HOME}/output
    - ./build/test/utest --gtest_filter=RndChecker*:GNetTest*:BoundGNetTest*:\FindConeTest*:FindCutTest*:SubstituteOptimizationCount*:RWDatabaseTest*:\SubstituteTest*:SubstitueCount*:TruthTableTest*:ParserVTest*:\AigPremapperTest*:MigMapperTest*:XagPremapperTest*:\XagPremapperVerilogTest*:XmgMapperTest*:toGraphMlTest*:\GateVerilogPrinter*:SimulatorGNetTest*:TransformerBDDGNetTest*:\MiniSatTest*:FLibraryDefaultTest*:ArithmeticTest*:FMTest*

  dependencies:
    - build_project
