image: isprasmvg/utopia-eda:clear

stages:
  - build
  - test

build_project:
  stage: build
  tags:
    - docker

  script:
    - rm -rf ${UTOPIA_HOME}/build
    - export UTOPIA_HOME=/builds/mvg/utopia-eda
    - cd ${UTOPIA_HOME}
    - git submodule init
    - git submodule update
    - cmake -S . -B build -G Ninja
    - cmake --build build

test_project:
  stage: test
  tags:
    - docker

  script:
    - rm -rf ${UTOPIA_HOME}/output
    - ${UTOPIA_HOME}/build/test/utest

  artifacts:
    paths:
      - build/
