image: isprasmvg/utopia-eda:clear

stages:
  - build

build_project:
  stage: build
  tags:
    - docker

  script:
    - rm -rf $UTOPIA_HOME/build
    - export UTOPIA_HOME=/builds/mvg/utopia-eda
    - cd UTOPIA_HOME
    - git submodule init
    - git submodule update
    - cmake -S . -B build -G Ninja
    - cmake --build build

  artifacts:
    paths:
      - build/
