FIRRTL version 3.2.0
circuit test :
  module adder_1bit :
    input co : UInt<1>
    input sum : UInt<1>
    input a : UInt<1>
    input b : UInt<1>
    input ci : UInt<1>
  module adder_2bit :
    input co : UInt<1>
    input sum : UInt<1>
    input a : UInt<1>
    input b : UInt<1>
    input ci : UInt<1>
  module adder_cla :
    input co : UInt<1>
    input sum : UInt<1>
    input a : UInt<1>
    input b : UInt<1>
    input ci : UInt<1>
  module test :
