
// Modified net example c17.
// Original net was generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1

module c17_modified(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7, B1;
  output N22, N23, B2, sign, sign2, out3;
  wire N1, N2, N3, N6, N7, B1, B2, sign, sign2;
  wire N22, N23, sign3;
  wire N10, N11, N16, N19, out3;
  nand NAND2_1 (N10, N1, N3);
  nand NAND2_2 (N11, N3, N6);
  nand NAND2_3 (N16, N2, N11);
  nand NAND2_4 (N19, N11, N7);
  nand NAND2_5 (N22, N10, N16);
  nand NAND2_6 (N23, N16, N19);

  assign B2 = B1;
  assign sign = 1'b1;
  assign sign2 = 1'b1;
  assign sign3 = 1'b1;

  not NOT1 (out3, sign3);

endmodule
